# The URL the site will be built for
base_url = "https://itanq.github.io"

title = "zmant"
default_language = "en"

compile_sass = true

highlight_code = true
highlight_theme = "base16-ocean-dark"

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

generate_rss = true
build_search_index = false
extra_syntaxes = ["syntaxes"]

[extra]
author = "zmant"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]
even_title = "zmant"
